version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - '/mnt/gluster_volume0/pihole/:/etc/pihole/'
      - '/mnt/gluster_volume0/dnsmasq/:/etc/dnsmasq.d/'
    networks:
      - pihole_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]

networks:
  pihole_network:
    driver: overlay